name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Retrieve tag
      run: |
        echo $(bash ./.github/tag.sh) >> $GITHUB_ENV
      id: tag
    - name: Build the Docker image
      run: docker build ./pi --file Dockerfile --tag uk-power-monitor:$(TAG)
